In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from sqlalchemy import create_engine
print("pandas:", pd.__version__)
print("requests:", requests.__version__)
print("All good — ready to build!")

pandas: 2.2.3
requests: 2.32.3
All good — ready to build!

In [8]:
import os
print(os.getcwd())

D:\job_market_intelligence

In [9]:
import pandas as pd

df = pd.read_csv('Data/raw/marketing_sample_for_naukri_com-jobs__30k_data.csv')

In [10]:
df.head(10)

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,Technical Support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,Software Test Engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer
5,c9628ea8d9cfd2ca72e14d53783aca90,2019-08-05 03:59:27 +0000,Opening For Adobe Analytics Specialist,"7,00,000 - 17,00,000 PA.",5 - 7 yrs,adobe experience manager| digital| digital ma...,Programming & Design,Pune,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",System Analyst
6,2008eb365fa0ebcb1ccd9a50efc3da49,2019-07-06 09:20:22 +0000,Sales- Fresher-for Leading Property Consultant,"2,00,000 - 3,00,000 PA.",0 - 0 yrs,channel partners| real estate| negotiation| p...,Retail Sales,Bengaluru,"Sales , Retail , Business Development","Real Estate, Property",Sales Executive/Officer
7,9642bed00e26183e41ab73778bf48108,2019-08-04 03:31:17 +0000,Opportunity For Azure Devops Architect For Hy...,Not Disclosed by Recruiter,9 - 14 yrs,TFS| Azure| Git| VSTS| Docker| DynaTrace| Spl...,Programming & Design,Hyderabad,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Architect
8,2633768efe8c6f72d75158f1c173f893,2019-07-06 15:41:47 +0000,BDE- PUNE,Not Disclosed by Recruiter,2 - 7 yrs,Bde,Institutional Sales,Pune,"Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
9,138a9ab97a766d8048f5b246172f65ed,2019-07-04 12:37:52 +0000,Technical Support/ Product Support,Not Disclosed by Recruiter,1 - 5 yrs,technical support| support services| applicat...,Voice,Bengaluru,"ITES , BPO , KPO , LPO , Customer Service , Op...","IT-Software, Software Services",Associate/Senior Associate -(Technical)

In [11]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Business question: What does our data look like?

df = pd.read_csv('Data/raw/marketing_sample_for_naukri_com-jobs__30k_data.csv')
print(f"Total job listings loaded: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print(f"\nColumn names: {list(df.columns)}")
df.head(3)

Total job listings loaded: 30000
Total columns: 11

Column names: ['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary', 'Job Experience Required', 'Key Skills', 'Role Category', 'Location', 'Functional Area', 'Industry', 'Role']

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive

In [12]:
# Business question: Is our data healthy? Where are problems hiding?

print("=== MISSING VALUES (nulls) per column ===")
print(df.isnull().sum())

print("\n=== TOTAL ROWS:", len(df), "===")
print("Rows with at least one missing value:", df.isnull().any(axis=1).sum())

print("\n=== DATA TYPE of each column ===")
print(df.dtypes)

=== MISSING VALUES (nulls) per column ===
Uniq Id                       0
Crawl Timestamp               0
Job Title                   575
Job Salary                   50
Job Experience Required     573
Key Skills                 1271
Role Category              2305
Location                    577
Functional Area             573
Industry                    573
Role                        901
dtype: int64

=== TOTAL ROWS: 30000 ===
Rows with at least one missing value: 2995

=== DATA TYPE of each column ===
Uniq Id                    object
Crawl Timestamp            object
Job Title                  object
Job Salary                 object
Job Experience Required    object
Key Skills                 object
Role Category              object
Location                   object
Functional Area            object
Industry                   object
Role                       object
dtype: object

In [13]:
list(df.columns)

['Uniq Id',
 'Crawl Timestamp',
 'Job Title',
 'Job Salary',
 'Job Experience Required',
 'Key Skills',
 'Role Category',
 'Location',
 'Functional Area',
 'Industry',
 'Role']

In [14]:
# Business question: How do we fix dirty data so we can trust our analysis?

# Step 1 — Rename columns (remove spaces, easier to type)
df.columns = ['id', 'crawl_date', 'job_title', 'salary',
              'experience', 'key_skills', 'role_category',
              'location', 'functional_area', 'industry', 'role']

# Step 2 — Drop rows where the 3 most important columns are missing
rows_before = len(df)
df.dropna(subset=['job_title', 'location', 'industry'], inplace=True)
rows_after = len(df)
print(f"Rows removed due to nulls: {rows_before - rows_after}")
print(f"Clean rows remaining: {rows_after}")

# Step 3 — Clean extra spaces and duplicates in location
# "Pune,Pune" → "Pune"
df['location'] = df['location'].str.strip()
df['location'] = df['location'].apply(
    lambda x: ', '.join(dict.fromkeys([c.strip() for c in x.split(',')])) if pd.notnull(x) else x
)

# Step 4 — Extract numbers from experience text
# "5 - 10 yrs" → min_exp = 5, max_exp = 10
df['exp_min'] = df['experience'].str.extract(r'(\d+)').astype(float)
df['exp_max'] = df['experience'].str.extract(r'\d+\s*-\s*(\d+)').astype(float)

# Step 5 — Fix the date column (text → proper date)
df['crawl_date'] = pd.to_datetime(df['crawl_date'], utc=True)

# Step 6 — Confirm everything looks right
print("\n=== NULLS AFTER CLEANING ===")
print(df[['job_title','location','industry','exp_min','exp_max']].isnull().sum())

print("\n=== SAMPLE OF EXPERIENCE EXTRACTION ===")
print(df[['experience','exp_min','exp_max']].dropna().head(5))

print("\n=== DATE COLUMN FIXED ===")
print(df['crawl_date'].dtype)
print(df['crawl_date'].head(3))

Rows removed due to nulls: 582
Clean rows remaining: 29418

=== NULLS AFTER CLEANING ===
job_title      0
location       0
industry       0
exp_min      173
exp_max      193
dtype: int64

=== SAMPLE OF EXPERIENCE EXTRACTION ===
   experience  exp_min  exp_max
0  5 - 10 yrs      5.0     10.0
1   2 - 5 yrs      2.0      5.0
2   0 - 1 yrs      0.0      1.0
3   0 - 5 yrs      0.0      5.0
4   2 - 5 yrs      2.0      5.0

=== DATE COLUMN FIXED ===
datetime64[ns, UTC]
0   2019-07-05 01:46:07+00:00
1   2019-07-06 08:04:50+00:00
2   2019-08-05 15:50:44+00:00
Name: crawl_date, dtype: datetime64[ns, UTC]

In [15]:
# Business question: Where are the jobs? 
# Which cities and industries are hiring most?
# Business question: Where are the jobs? 
# Which cities and industries are hiring most?

print("=== TOP 10 CITIES HIRING ===")
print(df['location'].value_counts().head(10))

print("\n=== TOP 10 INDUSTRIES ===")
print(df['industry'].value_counts().head(10))

print("\n=== TOP 10 JOB TITLES ===")
print(df['job_title'].value_counts().head(10))

print("\n=== EXPERIENCE LEVEL SUMMARY ===")
print(f"Average minimum experience required: {df['exp_min'].mean():.1f} years")
print(f"Most common experience range: {df['experience'].value_counts().index[0]}")

=== TOP 10 CITIES HIRING ===
location
Bengaluru    5220
Mumbai       3457
Pune         2523
Hyderabad    2295
Gurgaon      1814
Chennai      1647
Kolkata      1377
Delhi        1255
Noida        1181
Ahmedabad    1053
Name: count, dtype: int64

=== TOP 10 INDUSTRIES ===
industry
IT-Software, Software Services               10012
Recruitment, Staffing                         2721
BPO, Call Centre, ITeS                        1754
Banking, Financial Services, Broking          1685
Education, Teaching, Training                 1362
IT-Software / Software Services                786
Medical, Healthcare, Hospitals                 676
Internet, Ecommerce                            585
Construction, Engineering, Cement, Metals      566
Strategy, Management Consulting Firms          532
Name: count, dtype: int64

=== TOP 10 JOB TITLES ===
job_title
Business Development Executive    120
Sales Executive                   120
PHP Developer                     117
Business Development Manager       99
Graphic Designer                   84
Software Engineer                  79
Android Developer                  77
Java Developer                     77
Content Writer                     74
Sales Manager                      72
Name: count, dtype: int64

=== EXPERIENCE LEVEL SUMMARY ===
Average minimum experience required: 3.4 years
Most common experience range: 2 - 5 yrs

In [16]:
# Business question: What are the most in-demand skills 
# across all 30,000 job listings RIGHT NOW?

# Step 1 — Drop rows where skills are missing
skills_df = df['key_skills'].dropna()

# Step 2 — Split pipe-separated skills into individual items
# "Python| SQL| Excel" → ['Python', 'SQL', 'Excel']
skills_series = skills_df.str.split('|')

# Step 3 — explode() turns each skill into its own row
# One row with 3 skills becomes 3 rows with 1 skill each
skills_exploded = skills_series.explode()

# Step 4 — Clean spaces and fix capitalisation
skills_exploded = skills_exploded.str.strip().str.title()

# Step 5 — Count every skill
top_skills = skills_exploded.value_counts().head(20)

print("=== TOP 20 IN-DEMAND SKILLS (from 30,000 job listings) ===\n")
for rank, (skill, count) in enumerate(top_skills.items(), 1):
    bar = '█' * (count // 200)
    print(f"{rank:2}. {skill:<35} {count:>5}  {bar}")

=== TOP 20 IN-DEMAND SKILLS (from 30,000 job listings) ===

 1. Javascript                           2264  ███████████
 2. Sales                                1868  █████████
 3. Sql                                  1562  ███████
 4. Html                                 1540  ███████
 5. Customer Service                     1340  ██████
 6. Java                                 1234  ██████
 7. Python                               1177  █████
 8. Jquery                               1091  █████
 9. Business Development                 1079  █████
10. Recruitment                          1064  █████
11. Technical Support                    1030  █████
12. Management                            953  ████
13. Mysql                                 925  ████
14. Bpo                                   876  ████
15. C                                     821  ████
16. Project Management                    816  ████
17. Business Executive                    813  ████
18. Web Technologies                      801  ████
19. Linux                                 792  ███
20. Marketing                             764  ███

In [17]:
# Business question: Is this market fresher-friendly or 
# does everyone want experienced candidates?

# Step 1 — Categorise jobs by experience level
bins = [-1, 1, 3, 6, 10, 50]
labels = ['Fresher (0-1 yr)', 'Junior (1-3 yrs)', 
          'Mid (3-6 yrs)', 'Senior (6-10 yrs)', 
          'Expert (10+ yrs)']

df['exp_level'] = pd.cut(df['exp_min'], bins=bins, labels=labels)

# Step 2 — Count jobs per experience level
exp_counts = df['exp_level'].value_counts().sort_index()

print("=== JOB MARKET BY EXPERIENCE LEVEL ===\n")
total = exp_counts.sum()
for level, count in exp_counts.items():
    pct = (count / total) * 100
    bar = '█' * int(pct // 2)
    print(f"{level:<22} {count:>5} jobs  ({pct:.1f}%)  {bar}")

# Step 3 — Fresher friendly cities
print("\n=== TOP 5 FRESHER-FRIENDLY CITIES ===")
fresher_df = df[df['exp_min'] <= 1]
print(fresher_df['location'].value_counts().head(5))

# Step 4 — Fresher friendly industries  
print("\n=== TOP 5 FRESHER-FRIENDLY INDUSTRIES ===")
print(fresher_df['industry'].value_counts().head(5))

=== JOB MARKET BY EXPERIENCE LEVEL ===

Fresher (0-1 yr)        8766 jobs  (30.0%)  ██████████████
Junior (1-3 yrs)        9989 jobs  (34.2%)  █████████████████
Mid (3-6 yrs)           6502 jobs  (22.2%)  ███████████
Senior (6-10 yrs)       3157 jobs  (10.8%)  █████
Expert (10+ yrs)         831 jobs  (2.8%)  █

=== TOP 5 FRESHER-FRIENDLY CITIES ===
location
Bengaluru    1085
Mumbai        829
Kolkata       829
Pune          634
Gurgaon       552
Name: count, dtype: int64

=== TOP 5 FRESHER-FRIENDLY INDUSTRIES ===
industry
IT-Software, Software Services          2461
BPO, Call Centre, ITeS                  1270
Recruitment, Staffing                    838
Banking, Financial Services, Broking     469
Education, Teaching, Training            338
Name: count, dtype: int64

In [18]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

DB_USER = "postgres"
DB_PASSWORD = quote_plus("Deadshotff@152")

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "job_market_db"

engine = create_engine(
    f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version();"))
        print("PostgreSQL connected successfully!")
        print(result.fetchone()[0])

except Exception as e:
    print(f"Connection failed: {e}")

PostgreSQL connected successfully!
PostgreSQL 18.1 on x86_64-windows, compiled by msvc-19.44.35221, 64-bit

In [19]:
import sqlalchemy

In [20]:
# Push clean dataframe into PostgreSQL as a table
df.to_sql(
    name='job_listings',      # table name in database
    con=engine,               # connection we created
    if_exists='replace',      # if table exists, replace it
    index=False,              # don't write row numbers as a column
    dtype={                   # tell postgres what type each column is
        'id': sqlalchemy.Text(),
        'crawl_date': sqlalchemy.DateTime(timezone=True),
        'job_title': sqlalchemy.Text(),
        'salary': sqlalchemy.Text(),
        'experience': sqlalchemy.Text(),
        'key_skills': sqlalchemy.Text(),
        'role_category': sqlalchemy.Text(),
        'location': sqlalchemy.Text(),
        'functional_area': sqlalchemy.Text(),
        'industry': sqlalchemy.Text(),
        'role': sqlalchemy.Text(),
        'exp_min': sqlalchemy.Float(),
        'exp_max': sqlalchemy.Float(),
        'exp_level': sqlalchemy.Text(),
    }
)

print("Table created successfully!")
print(f"Total rows pushed: {len(df)}")

Table created successfully!
Total rows pushed: 29418

In [21]:
# SQL Query 1
# Business question: Which city has the most job opportunities?

query1 = """
SELECT 
    location,
    COUNT(*) as job_count
FROM job_listings
GROUP BY location
ORDER BY job_count DESC
LIMIT 10;
"""

result1 = pd.read_sql(query1, engine)
print("=== TOP 10 CITIES BY JOB COUNT ===\n")
print(result1.to_string(index=False))

=== TOP 10 CITIES BY JOB COUNT ===

 location  job_count
Bengaluru       5220
   Mumbai       3457
     Pune       2523
Hyderabad       2295
  Gurgaon       1814
  Chennai       1647
  Kolkata       1377
    Delhi       1255
    Noida       1181
Ahmedabad       1053

In [22]:
# SQL Query 2
# Business question: Which industry hires most freshers?

query2 = """
SELECT 
    industry,
    COUNT(*) as fresher_jobs
FROM job_listings
WHERE exp_min <= 1
GROUP BY industry
ORDER BY fresher_jobs DESC
LIMIT 10;
"""

result2 = pd.read_sql(query2, engine)
print("=== TOP 10 FRESHER FRIENDLY INDUSTRIES ===\n")
print(result2.to_string(index=False))

=== TOP 10 FRESHER FRIENDLY INDUSTRIES ===

                                           industry  fresher_jobs
                     IT-Software, Software Services          2461
                             BPO, Call Centre, ITeS          1270
                              Recruitment, Staffing           838
               Banking, Financial Services, Broking           469
                      Education, Teaching, Training           338
                     Medical, Healthcare, Hospitals           335
Travel , Hotels , Restaurants , Airlines , Railways           204
                                              Other           183
              Advertising, PR, MR, Event Management           164
                                Internet, Ecommerce           157

In [23]:
# SQL Query 3
# Business question: Which industries are hardest to enter?

query3 = """
SELECT 
    industry,
    ROUND(AVG(exp_min)::numeric, 1) as avg_experience,
    COUNT(*) as total_jobs
FROM job_listings
WHERE exp_min IS NOT NULL
GROUP BY industry
HAVING COUNT(*) > 100
ORDER BY avg_experience DESC
LIMIT 10;
"""

result3 = pd.read_sql(query3, engine)
print("=== INDUSTRIES REQUIRING HIGHEST EXPERIENCE ===\n")
print(result3.to_string(index=False))

=== INDUSTRIES REQUIRING HIGHEST EXPERIENCE ===

                                   industry  avg_experience  total_jobs
 Oil and Gas, Energy, Power, Infrastructure             5.3         313
  Construction, Engineering, Cement, Metals             4.7         564
            IT-Software / Software Services             4.6         786
  Chemicals, PetroChemical, Plastic, Rubber             4.5         147
                Semiconductors, Electronics             4.5         170
                      FMCG, Foods, Beverage             4.4         296
                   Electricals, Switchgears             4.3         115
Automobile, Auto Anciliary, Auto Components             4.3         498
            Textiles, Garments, Accessories             4.2         138
                                Telcom, ISP             4.0         294

In [24]:
# SQL Query 4
# Business question: Which city + industry combination 
# has the most job opportunities?

query4 = """
SELECT 
    location,
    industry,
    COUNT(*) as job_count
FROM job_listings
GROUP BY location, industry
ORDER BY job_count DESC
LIMIT 10;
"""

result4 = pd.read_sql(query4, engine)
print("=== TOP 10 CITY + INDUSTRY COMBINATIONS ===\n")
print(result4.to_string(index=False))

=== TOP 10 CITY + INDUSTRY COMBINATIONS ===

 location                       industry  job_count
Bengaluru IT-Software, Software Services       2179
     Pune IT-Software, Software Services        971
Hyderabad IT-Software, Software Services        965
   Mumbai IT-Software, Software Services        927
  Kolkata IT-Software, Software Services        893
  Chennai IT-Software, Software Services        594
  Gurgaon IT-Software, Software Services        506
Bengaluru          Recruitment, Staffing        493
    Noida IT-Software, Software Services        445
Ahmedabad IT-Software, Software Services        332

In [25]:
# SQL Query 5
# Business question: Which industries have more than 500 job listings?

query5 = """
SELECT 
    industry,
    COUNT(*) as job_count
FROM job_listings
GROUP BY industry
HAVING COUNT(*) > 500
ORDER BY job_count DESC;
"""

result5 = pd.read_sql(query5, engine)
print("=== INDUSTRIES WITH MORE THAN 500 JOB LISTINGS ===\n")
print(result5.to_string(index=False))

=== INDUSTRIES WITH MORE THAN 500 JOB LISTINGS ===

                                           industry  job_count
                     IT-Software, Software Services      10012
                              Recruitment, Staffing       2721
                             BPO, Call Centre, ITeS       1754
               Banking, Financial Services, Broking       1685
                      Education, Teaching, Training       1362
                    IT-Software / Software Services        786
                     Medical, Healthcare, Hospitals        676
                                Internet, Ecommerce        585
          Construction, Engineering, Cement, Metals        566
              Strategy, Management Consulting Firms        532
Travel , Hotels , Restaurants , Airlines , Railways        510

In [26]:
# SQL Query 6
# Business question: Which job roles have national demand
# appearing in more than 5 different cities?

query6 = """
SELECT 
    role,
    COUNT(DISTINCT location) as city_count,
    COUNT(*) as total_jobs
FROM job_listings
WHERE role IS NOT NULL
GROUP BY role
HAVING COUNT(DISTINCT location) > 5
ORDER BY city_count DESC
LIMIT 10;
"""

result6 = pd.read_sql(query6, engine)
print("=== TOP 10 ROLES WITH NATIONAL DEMAND ===\n")
print(result6.to_string(index=False))

=== TOP 10 ROLES WITH NATIONAL DEMAND ===

                                      role  city_count  total_jobs
                        Software Developer         463        6396
        Sales/Business Development Manager         415        1561
                   Sales Executive/Officer         322        1168
                                     Other         188         896
Associate/Senior Associate -(NonTechnical)         167        1725
                                   Fresher         129         380
                  Team Lead/Technical Lead         110         847
                     Recruitment Executive          99         427
             Accounts Executive/Accountant          89         511
                           Medical Officer          80         127

In [27]:
# SQL Query 7
# Business question: Rank all industries by job count
# Which is #1, #2, #3?

query7 = """
SELECT 
    industry,
    COUNT(*) as job_count,
    RANK() OVER (ORDER BY COUNT(*) DESC) as industry_rank
FROM job_listings
GROUP BY industry
ORDER BY industry_rank
LIMIT 10;
"""

result7 = pd.read_sql(query7, engine)
print("=== INDUSTRIES RANKED BY JOB COUNT ===\n")
print(result7.to_string(index=False))

=== INDUSTRIES RANKED BY JOB COUNT ===

                                 industry  job_count  industry_rank
           IT-Software, Software Services      10012              1
                    Recruitment, Staffing       2721              2
                   BPO, Call Centre, ITeS       1754              3
     Banking, Financial Services, Broking       1685              4
            Education, Teaching, Training       1362              5
          IT-Software / Software Services        786              6
           Medical, Healthcare, Hospitals        676              7
                      Internet, Ecommerce        585              8
Construction, Engineering, Cement, Metals        566              9
    Strategy, Management Consulting Firms        532             10

In [28]:
# SQL Query 8
# Business question: Which cities have highest 
# percentage of fresher jobs?

query8 = """
WITH city_total AS (
    SELECT 
        location, 
        COUNT(*) as total
    FROM job_listings
    GROUP BY location
),
city_fresher AS (
    SELECT 
        location, 
        COUNT(*) as fresher_jobs
    FROM job_listings
    WHERE exp_min <= 1
    GROUP BY location
)
SELECT 
    t.location,
    t.total,
    f.fresher_jobs,
    ROUND(f.fresher_jobs::numeric / t.total * 100, 1) as fresher_pct
FROM city_total t
JOIN city_fresher f ON t.location = f.location
WHERE t.total > 200
ORDER BY fresher_pct DESC
LIMIT 10;
"""

result8 = pd.read_sql(query8, engine)
print("=== CITIES WITH HIGHEST FRESHER JOB PERCENTAGE ===\n")
print(result8.to_string(index=False))

=== CITIES WITH HIGHEST FRESHER JOB PERCENTAGE ===

  location  total  fresher_jobs  fresher_pct
   Kolkata   1377           829         60.2
 Delhi NCR    767           286         37.3
 Ahmedabad   1053           362         34.4
Chandigarh    316           108         34.2
     Noida   1181           368         31.2
   Gurgaon   1814           552         30.4
   Chennai   1647           428         26.0
      Pune   2523           634         25.1
     Delhi   1255           307         24.5
    Mumbai   3457           829         24.0

In [29]:
import os

# Create the folders if they don't exist
os.makedirs('../data/cleaned', exist_ok=True)
os.makedirs('../data/raw', exist_ok=True)

print("Folders created!")

# Now save the clean CSV
df.to_csv('../data/cleaned/naukri_clean.csv', index=False)
print(f"Clean data saved! Rows: {len(df)}")

Folders created!
Clean data saved! Rows: 29418

In [30]:
df.head(10)

,id,crawl_date,job_title,salary,experience,key_skills,role_category,location,functional_area,industry,role,exp_min,exp_max,exp_level
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07+00:00,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager,5.0,10.0,Mid (3-6 yrs)
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50+00:00,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,Pune,"Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,2.0,5.0,Junior (1-3 yrs)
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44+00:00,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive,0.0,1.0,Fresher (0-1 yr)
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56+00:00,Technical Support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,0.0,5.0,Fresher (0-1 yr)
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29+00:00,Software Test Engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer,2.0,5.0,Junior (1-3 yrs)
5,c9628ea8d9cfd2ca72e14d53783aca90,2019-08-05 03:59:27+00:00,Opening For Adobe Analytics Specialist,"7,00,000 - 17,00,000 PA.",5 - 7 yrs,adobe experience manager| digital| digital ma...,Programming & Design,Pune,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",System Analyst,5.0,7.0,Mid (3-6 yrs)
6,2008eb365fa0ebcb1ccd9a50efc3da49,2019-07-06 09:20:22+00:00,Sales- Fresher-for Leading Property Consultant,"2,00,000 - 3,00,000 PA.",0 - 0 yrs,channel partners| real estate| negotiation| p...,Retail Sales,Bengaluru,"Sales , Retail , Business Development","Real Estate, Property",Sales Executive/Officer,0.0,0.0,Fresher (0-1 yr)
7,9642bed00e26183e41ab73778bf48108,2019-08-04 03:31:17+00:00,Opportunity For Azure Devops Architect For Hy...,Not Disclosed by Recruiter,9 - 14 yrs,TFS| Azure| Git| VSTS| Docker| DynaTrace| Spl...,Programming & Design,Hyderabad,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Architect,9.0,14.0,Senior (6-10 yrs)
8,2633768efe8c6f72d75158f1c173f893,2019-07-06 15:41:47+00:00,BDE- PUNE,Not Disclosed by Recruiter,2 - 7 yrs,Bde,Institutional Sales,Pune,"Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,2.0,7.0,Junior (1-3 yrs)
9,138a9ab97a766d8048f5b246172f65ed,2019-07-04 12:37:52+00:00,Technical Support/ Product Support,Not Disclosed by Recruiter,1 - 5 yrs,technical support| support services| applicat...,Voice,Bengaluru,"ITES , BPO , KPO , LPO , Customer Service , Op...","IT-Software, Software Services",Associate/Senior Associate -(Technical),1.0,5.0,Fresher (0-1 yr)

In [31]:
import os

print(os.path.abspath('../data/cleaned/naukri_clean.csv'))

D:\data\cleaned\naukri_clean.csv

In [32]:
import os

os.makedirs(
    r'D:\job_market_intelligence\Data\cleaned',
    exist_ok=True
)

df.to_csv(
    r'D:\job_market_intelligence\Data\cleaned\naukri_clean.csv',
    index=False
)

print("File saved successfully!")
print(f"Clean data saved! Rows: {len(df)}")

File saved successfully!
Clean data saved! Rows: 29418